#ifndef EMULATOR_VERSION_H
#define EMULATOR_VERSION_H

/* Name of the Emulator */
#define EMULATOR_NAME "LIBPSX"

/* Emulator version */
#define EMULATOR_MAJOR_VERSION (1)
#define EMULATOR_MINOR_VERSION (101)

/* Compile date and time */
#define EMULATOR_COMPILE_DATE (__DATE__)
#define EMULATOR_COMPILE_TIME (__TIME__)

/* Psy-Q version */
#define PSYQ_MAJOR_VERSION (4)
#define PSYQ_MINOR_VERSION (7)

#endif