#ifndef GAME_VERSION_N
#define GAME_VERSION_N		"7.6"
#endif

#ifndef GAME_VERSION_RES
#define GAME_VERSION_RES	7,6
#endif

#define GAME_TITLE			"REDRIVER2"
#define GAME_VERSION		GAME_TITLE " " GAME_VERSION_N
