#ifndef VERSION_H
#define VERSION_H

#ifndef GAME_VERSION_N
#define GAME_VERSION_N		"7.0"
#endif // GAME_VERSION_N

#define GAME_TITLE			"REDRIVER2"
#define GAME_VERSION		GAME_TITLE " " GAME_VERSION_N

#endif // VERSION_H