// WARNING: This file's extension ('.S') indicates that it may not have been a C or C++ file.
// It should contain Ghidra's best effort at decompiling the machine language to C, 
// but TDR does not currently attempt to handle assembly language or other non-C/C++ code differently, 
// so any decompiled code below may not reflect the original project source code for this file.
// If the source file is from a library, you should replace it with the original library version of the file.
// Otherwise, manual reconstruction of the code may be required, 
// Especially if the original source code was assembly language which used hardware features inaccessible to C.
#include "THISDUST.H"
#include "CMANASM.H"


// autogenerated function stub: 
// void g_black() /* g_black method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void g_black() 
{ // line 1, offset 0x001027e8
	/* begin block 1 */
		// Start line: 5
	/* end block 1 */
	// End Line: 6

	/* begin block 2 */
		// Start line: 6
	/* end block 2 */
	// End Line: 7

	/* begin block 3 */
		// Start line: 7
	/* end block 3 */
	// End Line: 8

	/* begin block 4 */
		// Start line: 8
	/* end block 4 */
	// End Line: 9

	/* begin block 5 */
		// Start line: 9
	/* end block 5 */
	// End Line: 10

	/* begin block 6 */
		// Start line: 10
	/* end block 6 */
	// End Line: 11

	/* begin block 7 */
		// Start line: 11
	/* end block 7 */
	// End Line: 12

	/* begin block 8 */
		// Start line: 12
	/* end block 8 */
	// End Line: 13

	/* begin block 9 */
		// Start line: 13
	/* end block 9 */
	// End Line: 14

	/* begin block 10 */
		// Start line: 14
	/* end block 10 */
	// End Line: 15

	/* begin block 11 */
		// Start line: 15
	/* end block 11 */
	// End Line: 16

	/* begin block 12 */
		// Start line: 16
	/* end block 12 */
	// End Line: 17

	/* begin block 13 */
		// Start line: 17
	/* end block 13 */
	// End Line: 18

	/* begin block 14 */
		// Start line: 18
	/* end block 14 */
	// End Line: 19

	/* begin block 15 */
		// Start line: 19
	/* end block 15 */
	// End Line: 20

	/* begin block 16 */
		// Start line: 20
	/* end block 16 */
	// End Line: 21

	/* begin block 17 */
		// Start line: 21
	/* end block 17 */
	// End Line: 22

	/* begin block 18 */
		// Start line: 22
	/* end block 18 */
	// End Line: 23

	/* begin block 19 */
		// Start line: 23
	/* end block 19 */
	// End Line: 24

	/* begin block 20 */
		// Start line: 24
	/* end block 20 */
	// End Line: 25

	/* begin block 21 */
		// Start line: 25
	/* end block 21 */
	// End Line: 26

	/* begin block 22 */
		// Start line: 26
	/* end block 22 */
	// End Line: 27

	/* begin block 23 */
		// Start line: 27
	/* end block 23 */
	// End Line: 28

	/* begin block 24 */
		// Start line: 28
	/* end block 24 */
	// End Line: 29

	/* begin block 25 */
		// Start line: 29
	/* end block 25 */
	// End Line: 30

	/* begin block 26 */
		// Start line: 30
	/* end block 26 */
	// End Line: 31

	/* begin block 27 */
		// Start line: 31
	/* end block 27 */
	// End Line: 32

	/* begin block 28 */
		// Start line: 32
	/* end block 28 */
	// End Line: 33

	/* begin block 29 */
		// Start line: 33
	/* end block 29 */
	// End Line: 34

	return null;
}


// autogenerated function stub: 
// void g_pointer() /* g_pointer method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void g_pointer() 
{ // line 33, offset 0x001028f0
	/* begin block 1 */
		// Start line: 67
	/* end block 1 */
	// End Line: 68

	/* begin block 2 */
		// Start line: 68
	/* end block 2 */
	// End Line: 69

	/* begin block 3 */
		// Start line: 69
	/* end block 3 */
	// End Line: 70

	/* begin block 4 */
		// Start line: 70
	/* end block 4 */
	// End Line: 71

	return null;
}


// autogenerated function stub: 
// void g_arrows() /* g_arrows method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void g_arrows() 
{ // line 38, offset 0x00102d68
	/* begin block 1 */
		// Start line: 77
	/* end block 1 */
	// End Line: 78

	/* begin block 2 */
		// Start line: 78
	/* end block 2 */
	// End Line: 79

	/* begin block 3 */
		// Start line: 79
	/* end block 3 */
	// End Line: 80

	/* begin block 4 */
		// Start line: 80
	/* end block 4 */
	// End Line: 81

	return null;
}


// autogenerated function stub: 
// void g_buttons() /* g_buttons method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void g_buttons() 
{ // line 49, offset 0x00103370
	/* begin block 1 */
		// Start line: 99
	/* end block 1 */
	// End Line: 100

	/* begin block 2 */
		// Start line: 100
	/* end block 2 */
	// End Line: 101

	/* begin block 3 */
		// Start line: 101
	/* end block 3 */
	// End Line: 102

	return null;
}


// autogenerated function stub: 
// void g_abcd() /* g_abcd method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void g_abcd() 
{ // line 77, offset 0x00103ff0
	/* begin block 1 */
		// Start line: 155
	/* end block 1 */
	// End Line: 156

	/* begin block 2 */
		// Start line: 156
	/* end block 2 */
	// End Line: 157

	/* begin block 3 */
		// Start line: 157
	/* end block 3 */
	// End Line: 158

	/* begin block 4 */
		// Start line: 158
	/* end block 4 */
	// End Line: 159

	/* begin block 5 */
		// Start line: 159
	/* end block 5 */
	// End Line: 160

	return null;
}


// autogenerated function stub: 
// void g_font0() /* g_font0 method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void g_font0() 
{ // line 94, offset 0x001043f8
	/* begin block 1 */
		// Start line: 189
	/* end block 1 */
	// End Line: 190

	/* begin block 2 */
		// Start line: 190
	/* end block 2 */
	// End Line: 191

	/* begin block 3 */
		// Start line: 191
	/* end block 3 */
	// End Line: 192

	/* begin block 4 */
		// Start line: 192
	/* end block 4 */
	// End Line: 193

	return null;
}


// autogenerated function stub: 
// void _6MCSLOT.s_init() /* _6MCSLOT.s_init method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void _6MCSLOT.s_init() 
{ // line 122, offset 0x0010eb40
	/* begin block 1 */
		// Start line: 245
	/* end block 1 */
	// End Line: 246

	/* begin block 2 */
		// Start line: 246
	/* end block 2 */
	// End Line: 247

	return null;
}




