// WARNING: This file's extension ('.S') indicates that it may not have been a C or C++ file.
// It should contain Ghidra's best effort at decompiling the machine language to C, 
// but TDR does not currently attempt to handle assembly language or other non-C/C++ code differently, 
// so any decompiled code below may not reflect the original project source code for this file.
// If the source file is from a library, you should replace it with the original library version of the file.
// Otherwise, manual reconstruction of the code may be required, 
// Especially if the original source code was assembly language which used hardware features inaccessible to C.
#include "THISDUST.H"
#include "FONT0.H"


// autogenerated function stub: 
// void g_font1() /* g_font1 method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void g_font1() 
{ // line 254, offset 0x001074cc
	/* begin block 1 */
		// Start line: 509
	/* end block 1 */
	// End Line: 510

	/* begin block 2 */
		// Start line: 510
	/* end block 2 */
	// End Line: 511

	/* begin block 3 */
		// Start line: 511
	/* end block 3 */
	// End Line: 512

	/* begin block 4 */
		// Start line: 512
	/* end block 4 */
	// End Line: 513

	/* begin block 5 */
		// Start line: 513
	/* end block 5 */
	// End Line: 514

	/* begin block 6 */
		// Start line: 514
	/* end block 6 */
	// End Line: 515

	/* begin block 7 */
		// Start line: 515
	/* end block 7 */
	// End Line: 516

	return null;
}




