// WARNING: This file's extension ('.S') indicates that it may not have been a C or C++ file.
// It should contain Ghidra's best effort at decompiling the machine language to C, 
// but TDR does not currently attempt to handle assembly language or other non-C/C++ code differently, 
// so any decompiled code below may not reflect the original project source code for this file.
// If the source file is from a library, you should replace it with the original library version of the file.
// Otherwise, manual reconstruction of the code may be required, 
// Especially if the original source code was assembly language which used hardware features inaccessible to C.
#include "THISDUST.H"
#include "MAINASM.H"


// autogenerated function stub: 
// void icon_0() /* icon_0 method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void icon_0() 
{ // line 1, offset 0x000a2800
	/* begin block 1 */
		// Start line: 5
	/* end block 1 */
	// End Line: 6

	/* begin block 2 */
		// Start line: 6
	/* end block 2 */
	// End Line: 7

	/* begin block 3 */
		// Start line: 7
	/* end block 3 */
	// End Line: 8

	/* begin block 4 */
		// Start line: 8
	/* end block 4 */
	// End Line: 9

	/* begin block 5 */
		// Start line: 9
	/* end block 5 */
	// End Line: 10

	/* begin block 6 */
		// Start line: 10
	/* end block 6 */
	// End Line: 11

	/* begin block 7 */
		// Start line: 11
	/* end block 7 */
	// End Line: 12

	/* begin block 8 */
		// Start line: 12
	/* end block 8 */
	// End Line: 13

	/* begin block 9 */
		// Start line: 13
	/* end block 9 */
	// End Line: 14

	/* begin block 10 */
		// Start line: 14
	/* end block 10 */
	// End Line: 15

	/* begin block 11 */
		// Start line: 15
	/* end block 11 */
	// End Line: 16

	/* begin block 12 */
		// Start line: 16
	/* end block 12 */
	// End Line: 17

	/* begin block 13 */
		// Start line: 17
	/* end block 13 */
	// End Line: 18

	/* begin block 14 */
		// Start line: 18
	/* end block 14 */
	// End Line: 19

	/* begin block 15 */
		// Start line: 19
	/* end block 15 */
	// End Line: 20

	/* begin block 16 */
		// Start line: 20
	/* end block 16 */
	// End Line: 21

	return null;
}


// autogenerated function stub: 
// void icon_1() /* icon_1 method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void icon_1() 
{ // line 20, offset 0x000a28c0
	/* begin block 1 */
		// Start line: 41
	/* end block 1 */
	// End Line: 42

	/* begin block 2 */
		// Start line: 42
	/* end block 2 */
	// End Line: 43

	return null;
}


// autogenerated function stub: 
// void icon_2() /* icon_2 method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void icon_2() 
{ // line 23, offset 0x000a2980
	/* begin block 1 */
		// Start line: 47
	/* end block 1 */
	// End Line: 48

	/* begin block 2 */
		// Start line: 48
	/* end block 2 */
	// End Line: 49

	/* begin block 3 */
		// Start line: 49
	/* end block 3 */
	// End Line: 50

	return null;
}




